version: '3'
services:

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: your_secret_key_here
    volumes:
      - ./dags:/opt/airflow/dags
      - E:/dbt_project/snowflake_data_project:/opt/airflow/dbt/snowflake_data_project
    ports:
      - "8085:8080"
    restart: always
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - E:/dbt_project/snowflake_data_project:/opt/airflow/dbt/snowflake_data_project
    restart: always
    command: scheduler

  airflow-init:
    image: apache/airflow:2.7.2
    depends_on:
      - airflow-webserver
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    entrypoint: /bin/bash
    command: >
      -c "airflow db init &&
          airflow users create
            --username admin
            --firstname Admin
            --lastname User
            --role Admin
            --email admin@example.com
            --password admin"
    volumes:
      - ./dags:/opt/airflow/dags
      - E:/dbt_project/snowflake_data_project:/opt/airflow/dbt/snowflake_data_project
